### ISSUE TITLE
Publish on apm

### ISSUE THREAD

**Issue by adius** [m-hall/eslint-fixer#1]
This is not yet published on apm, or is it?

**Comment by m-hall** [comment]
No I didn't publish it because I realized that the linter-eslint plugin already supports eslint --fix.
I simply added a menu option in my init script for it instead:

``` coffeescript
atom.contextMenu.add {
    'atom-workspace': [
        { label: 'Fix lint', command: 'linter-eslint:fix-file' }
    ]
}
```

I may still complete this package as I like the ability to use it from the tree view as well though.

**Comment by adius** [comment]
Ah OK. I'm using https://atom.io/packages/fast-eslint as linter-eslint didn't properly work for me.
But unfortunately it has no support for `--fix`…

**Comment by m-hall** [comment]
I'll try to finish it up later today. There wasn't much else that I wanted to include in the initial release for this anyway.

**Comment by m-hall** [comment]
FYI: I've released a version as eslint-fixer.
Sorry I didn't get to it earlier.

**Comment by adius** [comment]
No problem, thanks!
It seems to be a little buggy, however. =P
I already created a new issue…
