### ISSUE TITLE
When multiple file types supplied, it should "ignore" space

### ISSUE THREAD

**Issue by mikeerickson** [m-hall/eslint-fixer#10]

**Comment by mikeerickson** [comment]
If you have `fileTypes` as `js, jsx` it wont catch `jsx` file
If you have `fileTypes` as `js,jsx` it works as expected

Either strip the space when user defines (option two) or simply correctly parse the `fileTypes` to ignore space (it should work `as ext, ext` and `ext,ext` etc)

**Comment by mikeerickson** [comment]
This will be fixed in the next (version >=1.3) release 

![image](https://cloud.githubusercontent.com/assets/183153/22221234/ea89b37a-e166-11e6-9a6a-841fac68aa98.png)

**Comment by m-hall** [comment]
Fixed in 1.3.0.
Sorry for the delay
