### ISSUE TITLE
Continued Support?

### ISSUE THREAD

**Issue by mikeerickson** [m-hall/eslint-fixer#11]
Further, I am curious if you plan to support this moving forward, or would it be better served for me to continue with my plan of forking and adding the features (issues) I have mentioned.

**Comment by m-hall** [comment]
If you'd like to take ownership of this plugin you're welcome to do it. It appears that I won't really have time to be working on it much for the foreseeable future.
Part of the reason that I let this one in particular slip originally was because it's a feature that's actually already supported by [linter-eslint](https://atom.io/packages/linter-eslint). The only thing missing from it is that it's not exposed in any of the menus.
If you do make any pull requests though I'm willing to at least verify/merge and create new releases if you'd rather not take full ownership. Alternatively I could make you a collaborator, which should allow you to make updates and create releases whenever you have time for it.

**Comment by m-hall** [comment]
Regarding linter-eslint:
I had actually considered basically replacing the contents of this plugin with something like
```
atom.contextMenu.add {
    'atom-workspace': [
        { label: 'Fix lint', command: 'linter-eslint:fix-file' }
    ]
}
```
So that it lets users have the context-menu option, while having the same support that linter-eslint gives.

**Comment by mikeerickson** [comment]
@m-hall I have no problem taking over and maintaining.  But, your comment above has piqued my interest (doing some due diligence).

Where would you add this section?

**Comment by m-hall** [comment]
Personally I have used it in my user init script. Putting it in the plugin's activate would also work.

You could also do a similar thing with the menu cson files though. They don't require you to only show menu items for "this" plugin, it's just the most common use case.

**Comment by m-hall** [comment]
See #1 for details on why I didn't go that route at the time.

**Comment by mikeerickson** [comment]
I am trying to get a simple plugin work, but atom is throwing error on startup.   In my plugin activate method, I have the following:

```
        atom.contextMenu.add (
          'atom-workspace',
	 {
            label: 'Fix Lint',
	    command: 'linter-eslint:fix-file'				
         }
        );

```

Error from atom

![image](https://cloud.githubusercontent.com/assets/183153/22219210/c67357d2-e15e-11e6-8d0c-014ed70080ef.png)

**Comment by m-hall** [comment]
It actually translates to this in JS
```JavaScript
atom.contextMenu.add(
    {
        'atom-workspace': [
            {
                label:'Fix lint',
                command:'linter-eslint:fix-file'
            }
        ]
    }
)
```

**Comment by mikeerickson** [comment]
Ahhh, snap!  Forgot the outter object :-)

**Comment by mikeerickson** [comment]
OK, all is now working like a charm :-)   I have added the above to the plugin and all is cool.

**Comment by mikeerickson** [comment]
The only place it does not work is when selecting it in the sidebar...  Menu item appears, but selecting it does nothing.  I am sure there is a logical reason for that, just havent dug into it yet.

**Comment by m-hall** [comment]
The sidebar would still only fix the "current open file" if you use linter-eslint. Their action is not designed to handle sidebar in any way.

**Comment by mikeerickson** [comment]
No worries, all is working as I want (and I am sure will be fine).

**Comment by m-hall** [comment]
That's actually why this plugin has a separate action for "run-tree-view".
And also another reason why I didn't completely deprecate this plugin.

**Comment by mikeerickson** [comment]
OK, I have everything working from both menu and contextual menu (disabled sidebar for the moment).  Next thing I will be adding is a default keymap.

**Comment by mikeerickson** [comment]
@m-hall I have made all the edits, etc 

How would you like to go about changing ownership?

**Comment by m-hall** [comment]
If your new version is going to be specific to linter-eslint, then I would suggest releasing it as a separate package. That way support for people not using it can continue and I'll try to get some time in the near future to try to fix it up. I will also add notes on the README about using yours for people using linter-eslint.

If you want to take over this one without linter-eslint support, then I can make you a collaborator of this repo, which should give you rights to push to master and create new versions on APM.

If you want to support for linter-eslint if available and have backup options, then I would do that as part of this repo and you would be a collaborator on it, with the permissions noted above..

**Comment by mikeerickson** [comment]
OK, I am cool with all of that.  I would like to support sidebar as well.  I have already added support for the new settings item (eslint binary and fixes for fileTypes).

**Comment by mikeerickson** [comment]
And, I have cleaned up the README as well (expanded information, etc.)

**Comment by m-hall** [comment]
Cool, I've added you as a collaborator, so you can push anytime you want now.

**Comment by mikeerickson** [comment]
@m-hall Thanks, and thx for your guidance.
