### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by RobbieTheWagner** [m-hall/eslint-fixer#3]
Does not fix the file

**Comment by m-hall** [comment]
1) need a lot more context
2) This plugin doesn't fix the file, it simply runs eslint --fix on the file. Not all of the rules are fixable, and some rules (like indenting) may require multiple runs. That however is a bug with eslint --fix.

**Comment by m-hall** [comment]
Also, it does not work if the file has unsaved changes.

**Comment by RobbieTheWagner** [comment]
I just purposefully unindented a line, saved, and ran it, and nothing happened. I'm just using the main eslint linter now, which has an option to fix on save.

**Comment by esutton** [comment]
I do not see any difference after running 1.2.1 in Atom.


![screen shot 2016-12-01 at 9 14 35 am](https://cloud.githubusercontent.com/assets/6115047/20799052/a23c05b2-b7a6-11e6-8592-6c1d8230aa09.png)

**Comment by asdine** [comment]
Doesn't work for me either :(

**Comment by esutton** [comment]
I may abandon Atom for [Visual Studio Code](https://code.visualstudio.com/).  

The ESLint Fix works in  [Visual Studio Code](https://code.visualstudio.com/).  

<img width="252" alt="screen shot 2016-12-10 at 2 38 54 pm" src="https://cloud.githubusercontent.com/assets/6115047/21076015/6d369674-bee6-11e6-82c6-40e35b5a8917.png">

**Comment by asdine** [comment]
The [Linter-Eslint](https://atom.io/packages/linter-eslint) package has an option to fix on save:

<img width="556" alt="capture d ecran 2016-12-10 a 22 04 15" src="https://cloud.githubusercontent.com/assets/2102036/21076162/a3c71324-bf24-11e6-97a9-4f829e0cb6a6.png">

**Comment by esutton** [comment]
I manually pressed save before running.  Still nothing seems to fix?

My problem may be with Atom configuration and setup.  For me  [Visual Studio Code](https://code.visualstudio.com/), seemed easier to get ESLint fix working.  

However, there are a number of plugins and features that I think Atom does better.

**Comment by mikeerickson** [comment]
@rwwagner90 @esutton @asdine Hey gang...

If you are still using this plugin, I am going to be taking over ownership, etc. and fixing issues.  I have a full working version in my local forked repo and doing some cleanup etc.

**Comment by esutton** [comment]
@mikeerickson I switched to  [Visual Studio Code](https://code.visualstudio.com/) because of this issue. 

But thanks for the notice and sharing your work.
   https://github.com/mikeerickson/eslint-fixer

 I may give Atom another try.

**Comment by mikeerickson** [comment]
@esutton I tried Code myself and I just had too many little issues (lack of plugin ecosystem compared to atom

**Comment by asdine** [comment]
@mikeerickson I'm using the  [Linter-Eslint](https://atom.io/packages/linter-eslint) package that has an option that does the job for me.
But thank you !

**Comment by mikeerickson** [comment]
@aside Ya, I am actually using it under the hood.  On feature that `eslint-fixer` provides is support for executing linter from sidebar.  Oh, and I added a built-it keymap `ctrl-shift-f`

**Comment by kwerle** [comment]
Oh.  linter-eslint has the apply --fix on save.

You might just add a note for this repo to that affect and shut this down.

**Comment by m-hall** [comment]
This may be fixed with 1.3.0. If it is, please close this issue.
