### ISSUE TITLE
Utilize local, not global eslint installation

### ISSUE THREAD

**Issue by jaydenseric** [m-hall/eslint-fixer#7]
It is bad practice to globally install dependencies, each local project has config specific to it's yarn.lock installed version of the eslint dev dependency.

Could this tool be enhanced to look for a local eslint installation before looking for a global one? This is the behavior of other plugins such as [linter-eslint](https://github.com/AtomLinter/linter-eslint).

**Comment by mikeerickson** [comment]
@jaydenseric Hey Jay...

Just forked this repo and am going to add a setting to use the local eslint `./node_modules/.bin/eslint` instead of requiring global installation of eslint and any rules, etc.

**Comment by mikeerickson** [comment]
This will be fixed in the next (version >=1.3) release 

![image](https://cloud.githubusercontent.com/assets/183153/22221234/ea89b37a-e166-11e6-9a6a-841fac68aa98.png)

**Comment by campbecf** [comment]
Any updates on this?

**Comment by m-hall** [comment]
Fixed in 1.3.0.
Sorry for the delay
